### ISSUE TITLE
일부 웰에서 기존 방식 대비 RFU값 반토막

### ISSUE THREAD

**Issue by jhhan25** [ympaik87/rfu#10]
data: \14.32.167.236\기술혁신팀$\05-7. 장비개발\soonjoo_test\32W Real Time\RT bio data\190321\2호기 all3gi _ detection포함 (O)

문제점 - 일부 웰에서 기존 방식 대비 RFU 추출값 반토막 (다른 웰은 비교적 동등 수준)
전채널 : A4, B4, C4, D4

P2R 버전 : 4/11, PM 8시 기준 최신 (4f5e735)

새 방식 추출 데이터 위치 : \14.32.167.236\기술혁신팀$\05-7. 장비개발\soonjoo_test\32W Real Time\RT bio data\190321\2호기 all3gi _ detection포함 (O)\DSP_datasheet\QuantStep60

기존 방식 추출 데이터 위치 : \14.32.167.236\기술혁신팀$\07-1. 장비성능검증\02. SRT Cycler (32w, real-time)\02. SRT 2호기 (증폭 well산포, 형광신호)\20190321_RT 2호기_GI-V_3차 test\PGR cycler 결과분석\PGR분석\QuantStep60
(data1 - block1, data2-block2)

[2호기 all3gi _ detection포함 (O) 4f5e735 -  Quantitation Amplification Results.xlsx](https://github.com/ympaik87/rfu/files/3068595/2.all3gi._.detection.O.4f5e735.-.Quantitation.Amplification.Results.xlsx)
[data1.-.Quantitation.Amplification.Results.xlsx](https://github.com/ympaik87/rfu/files/3068598/data1.-.Quantitation.Amplification.Results.xlsx)

**Comment by ympaik87** [comment]
![Result_3ded23e-main_44_0_h](https://user-images.githubusercontent.com/1518669/56018369-e8670f80-5d3c-11e9-8af3-64c4174ffc51.jpg)
처음 자르는부분을 조정하면 해결 가능할 거로 보임
