### ISSUE TITLE
Grid 인식 오류

### ISSUE THREAD

**Issue by Keumhee** [ympaik87/rfu#11]
![Result_8d690a2-sub_44_0_q6](https://user-images.githubusercontent.com/49701806/56484136-fff68300-6508-11e9-91ae-f8206ff92e7c.jpg)

* data 위치입니다.
\\14.32.167.236\기술혁신팀$\05-7. 장비개발\soonjoo_test\20190417 TAT단축_new camera_Entero retest

마지막 Cycle image에서 grid 위치가 제대로 인식되지 않는 것으로 보입니다.

**Comment by ympaik87** [comment]
reference image를 다른 채널로 수정하는 것으로 해결
