### ISSUE TITLE
광학신호 미인식 현상

### ISSUE THREAD

**Issue by cimile08** [ympaik87/rfu#14]
- data : Z:\07-1. 장비성능검증\07. 광학계 신호수준 확인 테스트\20190521_1_SGSRT장비 raw data\data\Single result 모음\2. 1-4\Single_Result_f131c46-F_2.jpg

- 문제점 : A4 위치의 형광신호가 정상으로 보이나 RFU 추출 과정에서 신호로 인식하지 않음.
![Single_Result_f131c46-F_2](https://user-images.githubusercontent.com/49474881/58443898-0394af80-8130-11e9-917a-d526e59e60a6.jpg)

**Comment by ympaik87** [comment]
![Single_Result_82019f6-F_2-190528_131511](https://user-images.githubusercontent.com/1518669/58450628-b3771680-814a-11e9-8617-cffeff1f2960.jpg)

* 좌측 상단의 노이즈 물체때문에 grid영역이 의도한 영역보다 위로 잡히는게 버그의 원인.
* 해당 버그는 임시적으로 위에 노이즈 영역을 잘라내서 해결 가능
* 알고리즘 수정은 하드웨어가 안정화가 되면 잡아나갈 계획

**Comment by ympaik87** [comment]
위 사진의 x_range, y_range는 다음과 같음
```
self.y_range = slice(500, 2100)
self.x_range = slice(600, 2200)
```
