### ISSUE TITLE
lens array test 결과 분석을 위한 코드 수정 요청

### ISSUE THREAD

**Issue by Keumhee** [ympaik87/rfu#15]
lens array 사용 여부에 따른 광학 산포를 확인하고자
lens 사용 전/후,  5개 channel, 각 channel당 100번 촬영하였습니다.
폴더단위로 분석할 수 있도록 코드 수정 요청드립니다.

폴더구조 및 분석 대상 파일은 아래 위치의 폴더에서 확인 부탁드립니다.
\\14.32.167.236\기술혁신팀$\05-7. 장비개발\카메라실험\20190529 광학산포테스트

감사합니다!

**Comment by ympaik87** [comment]
self.y_range = slice(300, 1800)
self.x_range = slice(500, 2100)

**Comment by ympaik87** [comment]
59fdc0429c7818a510856521374a7cbea31c2691 면적이 같은 웰 신호 시 하나만 인식 되던 버그 해결
