### ISSUE TITLE
일부 웰에서 RFU값 0

### ISSUE THREAD

**Issue by jhhan25** [ympaik87/rfu#4]
data: \\14.32.167.236\기술혁신팀$\05-7. 장비개발\soonjoo_test\32W Real Time\RT bio data\190321\2호기 all3gi _ detection포함 (O)

문제점 - 일부 웰에서 RFU 추출값 0 (기존 방식 추출에서는 값 존재)
FAM,Q670,C610 : B7,B8,C5,C6
HEX : A4,B7,B8,C5,C6,D1,D4
Q705 : B6,B7,B8,C5,D2,D3

새 방식 추출 데이터 위치 : \\14.32.167.236\기술혁신팀$\05-7. 장비개발\soonjoo_test\32W Real Time\RT bio data\190321\2호기 all3gi _ detection포함 (O)\DSP_datasheet\QuantStep60

기존 방식 추출 데이터 위치 : \\14.32.167.236\기술혁신팀$\07-1. 장비성능검증\02. SRT Cycler (32w, real-time)\02. SRT 2호기 (증폭 well산포, 형광신호)\20190321_RT 2호기_GI-V_3차 test\PGR cycler 결과분석\PGR분석\QuantStep60
(data1 - block1, data2-block2)

[2호기 all3gi _ detection포함 (O) -  Quantitation Amplification Results.xlsx](https://github.com/ympaik87/rfu/files/3062704/2.all3gi._.detection.O.-.Quantitation.Amplification.Results.xlsx)
[data1 -  Quantitation Amplification Results.xlsx](https://github.com/ympaik87/rfu/files/3062705/data1.-.Quantitation.Amplification.Results.xlsx)
[data2 -  Quantitation Amplification Results.xlsx](https://github.com/ympaik87/rfu/files/3062706/data2.-.Quantitation.Amplification.Results.xlsx)

**Comment by ympaik87** [comment]
대부분의 문제는 #3 이슈의 ROI영역 설정을 바꿈으로서 해결 됨
