### ISSUE TITLE
Command line 에서 Index Error 발생

### ISSUE THREAD

**Issue by cimile08** [ympaik87/rfu#5]
* Data : 기술혁신팀$:\07-1. 장비성능검증\02. SRT Cycler (32w, real-time)\04. SRT 3호기 (형광신호)\20190403_RT 3호기_Real-time test_GI-V_1차 test

* 문제점 : RFU CLI 에서 pix2rfu.py 실행 명령 시 Index error 발생함.

* 특이사항 :
 1) 대상 폴더에 main, sub 폴더 외에 다른 파일들 다수 존재.
 2) 대상 폴더의 main, sub 폴더 내에 RFU를 추출한 이미지파일 외 다른 파일들 다수 존재. 

![image](https://user-images.githubusercontent.com/49474881/55870634-f8a7af00-5bc3-11e9-88ad-434016e49fa3.png)

**Comment by ympaik87** [comment]
웰 grid를 설정하는 기준이 되는 이미지는 45싸이클, FAM채널의 이미지 사용. 현 데이터는 해당 싸이클에 검은색 이미지라 인식할 물체가 없어서 에러 발생

**Comment by ympaik87** [comment]
3호기 자체 문제로 판단하여 HW개선으로 해당 이슈 개선 예정
